# Generated by Django 6.0.3 on 2026-03-09 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_reviwew_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviwew',
            new_name='review',
        ),
    ]
